### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by alperyilmaz** [Xadeck/jekyll-terminal#3]
Sorry, I'm not a ruby guy, so this question might be too novice. I couldn't activate the plugin. The error message is:

```
Dependency Error: Yikes! It looks like you don't have jekyll-terminal or one of its \
dependencies installed. In order to use Jekyll as currently configured, you'll need to \
install this gem. The full error message from Ruby is: 'Unable to activate \ 
jekyll-terminal-0.1.2, because jekyll-3.1.3 conflicts with jekyll (~> 2.0)'
```

My system has the following versions:

```
$ ruby --version
ruby 2.0.0p384 (2014-01-12) [x86_64-linux-gnu]

$ jekyll --version
jekyll 3.1.3
```

Your spec defines dependencies as

```
s.add_runtime_dependency 'jekyll', ['>= 2.0', '< 4.0']
s.required_ruby_version = '~> 2.0'
```

So my versions should be okay. What seems to be the problem?
Thanks for developing this beautiful plugin.

**Comment by alperyilmaz** [comment]
I noticed that the plugin required **greater than** (not equal to) ruby version 2.0. So, I decided to upgrade ruby version. I used rbenv and upgraded to ruby version as follows.

```
$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

$ jekyll --version
jekyll 3.1.3
```

And I'm still getting the same error `Unable to activate jekyll-terminal-0.1.2, because jekyll-3.1.3 conflicts with jekyll (~> 2.0)` 

Can you please guide? I'm really confused with keeping up with gem versions and incompatibilities between them.

**Comment by Xadeck** [comment]
Apparently I was too restrictive when I set the requirements [1]. It only accepts ruby version between 2.0 and <2.1. I'm will have a look tonight and try to release a new version.

[1] https://robots.thoughtbot.com/rubys-pessimistic-operator

**Comment by Xadeck** [comment]
This said, on my fresh machine:

$ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
$ jekyll --version
jekyll 3.1.3
$ sudo gem install jekyll-terminal
Successfully installed jekyll-terminal-0.1.2
Parsing documentation for jekyll-terminal-0.1.2
Done installing documentation for jekyll-terminal after 0 seconds
1 gem installed

So it maybe something on your machine.

**Comment by alperyilmaz** [comment]
Maybe I mis-wrote my question. `gem install jekyll-terminal` works okay but jekyll gives error during build. Does it successfully build a website which uses jekyll-terminal plugin in your machine?

**Comment by Xadeck** [comment]
I hadn't touch that gem for ~2 years. Spend the night refreshing my ruby-fu. Pushed a new version (0.1.3) and tested it locally on my machine. I was able to generate a site with a terminal tag.

$ ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
$ gem --version
2.0.14.1
$ gem list jekyll-terminal

**\* LOCAL GEMS ***

jekyll-terminal (0.1.3)

Can you tell me if it works for you now? Oh, BTW, the problem may be that you have forgotten to add the following line to your _config.yml in the generated jekyll directory for your site.

gems: 
- jekyll-terminal

I've updated my README to explain that.

**Comment by alperyilmaz** [comment]
Sorry for troubling you with this, I must have ruined your night :(

But, it works, as shown below:

![selection_248](https://cloud.githubusercontent.com/assets/410615/15210639/0467e866-1840-11e6-9b67-92c906ddd65b.png)

Thanks a bunch.. I really appreciate your effort..

**Comment by Xadeck** [comment]
Hey, it looks nice! Glad it works. I noticed a small CSS problem though (on my machine, but also on your screenshot above). There is a small white frame that was not there before. I'll fix that soon. In the meantime, closing this issue since this is solved.
