### ISSUE TITLE
Display problem with absolute paths

### ISSUE THREAD

**Issue by VincentTam** [Xadeck/jekyll-terminal#4]
I tried including command output which contains absolute paths in [my blog post](https://git.io/vDJPf).

### Input

```
{% terminal %}
$ locate stdio.h
/usr/include/stdio.h
/usr/include/c++/4.8/tr1/stdio.h
/usr/include/x86_64-linux-gnu/bits/stdio.h
/usr/lib/perl/5.18.2/CORE/nostdio.h
{% endterminal %}
```

### Expected output

```
$ locate stdio.h
/usr/include/stdio.h
/usr/include/c++/4.8/tr1/stdio.h
/usr/include/x86_64-linux-gnu/bits/stdio.h
/usr/lib/perl/5.18.2/CORE/nostdio.h
```

### Actual output

```
$ locate stdio.h
usr/include/stdio.h
usr/include/c++/4.8/tr1/stdio.h
usr/include/x86_64-linux-gnu/bits/stdio.h
usr/lib/perl/5.18.2/CORE/nostdio.h
```

*All* lines are treated as command *input*.  How can the slash `/` at the beginning of each line be escaped?

**Comment by Xadeck** [comment]
One simple fix is to add a space at the beginning of each line.

But I reckon that's ugly. Hmmm. I should probably use another character, but doing that will break existing use  case, so I'd have to make it an option. Let me work on a fix today.

**Comment by Xadeck** [comment]
I've added an option to configure the continuation string (pushed in version 0.1.4). Let me know if that works for you.
